### ISSUE TITLE
ObjectMapper

### ISSUE THREAD

**Issue by dustintownsend** [erkie/ApiModel#17]
Any thoughts on using [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper/) for mapping the responses to Realm Objects?

**Comment by erkie** [comment]
@dustintownsend: I hadn't heard about it previously! It looks cool. Do you have any experience with it? Any pros/cons? In my usage of ApiModel I haven't required any more complex transform logic. What do you think it would bring in terms of added value?

Thanks!

**Comment by erkie** [comment]
We'll probably not be going down this route any time soon. So closing this for now!
