### ISSUE TITLE
rootNamespace property is never used 

### ISSUE THREAD

**Issue by tcrous** [erkie/ApiModel#22]
The rootNamespace property is never used and has no effect. Responses in format:

{"status":"ok","data":{"contacts":[{"id":"1","firstname":"jack","lastname":"white","prefi ...

Can therefore not be handled by specifying `config.rootNamespace = "data"`

**Comment by erkie** [comment]
Thanks for reporting this! It has been fixed now as of: https://github.com/erkie/ApiModel/commit/2fa29a1a0af4430653c5a7b462877e48ed092a37 I'll make a release soon.
