### ISSUE TITLE
NSDateTransformTests.testUserDefinedDateFormat Test is failing

### ISSUE THREAD

**Issue by cheneveld** [erkie/ApiModel#28]
Assertions: XCTAssertEqual failed: ("Optional("2015-12-30")") is not equal to ("Optional("2015-12-29")") - 
  File: NSDateTransformTests.swift:68

https://www.dropbox.com/s/eoykto1ti3jgo31/Screenshot%202016-01-19%2009.54.56.png?dl=0

**Comment by erkie** [comment]
Thanks for reporting that! I think the previous rewrite I did was buggy in that the `NSDateFormatter` in `NSDateTransform` was using the device local time zone when parsing, which resulted in weird offsets. I have a feeling this might cause issues in client code though... Please be cautious of any potential issues that might arise!

**Comment by cheneveld** [comment]
https://github.com/erkie/ApiModel/pull/31 has a update to this test that fixes it, another it uses now rather than a hard coded string.  these tests need more work and consideration.
