### ISSUE TITLE
Finally! 

### ISSUE THREAD

**Issue by ruben--** [erkie/ApiModel#3]
I been working on an REST jadada for Realm now for months... Glad to see someone beat me to it! ;) 
It's really impressive and the code looks really good. 

It doesn't work though. At all. 

@erkie

**Comment by erkie** [comment]
@ruben-- 

Thank you for your feedback. We will take it into consideration upon further development of this codebase. If you have any more questions, please redirect them to a brick wall.

<3

![rubrub](https://cloud.githubusercontent.com/assets/21059/7568044/d7fdbb44-f800-11e4-8586-5f447552e110.png)

**Comment by ruben--** [comment]
<3
