### ISSUE TITLE
need to be able to use a custom Alamofire manager rather than just the sharedInstance

### ISSUE THREAD

**Issue by wainglaister** [erkie/ApiModel#34]
If any configuration of the Alamofire manager is required there is currently an issue getting access to that as the sharedInstance is the only option. It should be possible to create and supply a custom manager instance.

**Comment by erkie** [comment]
This has been solved in a branch by @cheneveld. @cheneveld maybe you could add this and make a separate PR?

**Comment by wainglaister** [comment]
I've just started playing around, but my initial cut simply adds a manager to the config and uses that, so it's a 2 line change:

ApiConfig.swift line 5
- public var manager: Manager = Manager.sharedInstance

ApiManager.swift line 108
- config.manager.request(

I can create a PR for this at some point if required.

**Comment by erkie** [comment]
Closed by https://github.com/erkie/ApiModel/pull/36
