### ISSUE TITLE
Objective-c compatibility

### ISSUE THREAD

**Issue by markst** [erkie/ApiModel#39]
Is it possible to reference API requests in Objective c?

**Comment by markst** [comment]
I've been able to create a proxy such as:

``` swift
import Foundation
import ApiModel
import RealmSwift

@objc class APIProxy: NSObject {
    class func get(path: String, parameters: RequestParameters, completionHandler: (succeeded: Bool, array: [Object]?) -> ()) {
        Api<Bet>.get(path, parameters: parameters) { response in
            completionHandler(succeeded: response.isSuccessful, array: response.array)
        }
    }
}
```

Perhaps this is something I deal with for my project, rathe than a library issue.

**Comment by erkie** [comment]
I'm not completely sure what this does or how it works, but glad you found a workaround. Closing this, if you have a concrete suggestion about what it should look like from a library perspective, feel free to re-open! :)
