### ISSUE TITLE
Store a primary key to different attribute to payload id

### ISSUE THREAD

**Issue by markst** [erkie/ApiModel#41]
My response payload primary key is "id"
However I wish to store it in my model as "primaryKey".

**Comment by markst** [comment]
an exception is raised:

```
2016-04-01 18:13:02.028 ApiModelDemo[44226:743683] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<RLMStandalone_Bet 0x7fc16406d550> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key id.'
```

**Comment by markst** [comment]
``` swift
dynamic var pk    = ""
dynamic var title = ""

override class func primaryKey() -> String {
    return "pk"
}
class func fromJSONMapping() -> JSONMapping {
    return [
        "id"    : ApiIdTransform(),
        "title" : StringTransform(),
    ]
}
```

**Comment by markst** [comment]
Either I'm misunderstood or the `updateRealmObjectFromDictionaryWithMapping` needs to consider that `ApiIdTransform()` should map to the defined `primaryKey()`...

**Comment by markst** [comment]
#33

**Comment by erkie** [comment]
Yes, this is the same as #33 which ApiModel currently doesn't support. The original https://github.com/izettle/api-model supports attribute "synonyms", which is a nice way of dealing with these things. Closing this issue in favor of #33
