### ISSUE TITLE
Deleting records from Realm that are not in the API response

### ISSUE THREAD

**Issue by markst** [erkie/ApiModel#42]
Is possible to have orphaned objects identified & deleted?

**Comment by erkie** [comment]
That seems more like a realm-thing. What do you mean by orphaned objects? Will close this issue but feel free to open it if it is something that should be added to ApiModel! :)

**Comment by markst** [comment]
@erkie sorry, should have been clearer.

So a common setup for us is to have a table view display a load of results from the local data store. Then as the user scrolls, network requests are fetched with the pages of results. 

The server returns pages of results, but the local store would not update to 'delete' the results which are not returned by the server.

**Comment by markst** [comment]
one solution is to not update the table view with results until they're returned. but sometimes we have over a 1000 results & it's a nicer user experience for users to be able to scroll quickly through already cached results.

**Comment by markst** [comment]
A solution we have used is to pass the currently visible results or entire page size as params of object ids. Then the backend will identify if any no longer exist on the server, returning any deleted objects as 'deleted ids' meta...
